export const SET_LOADING = 'REDUX_THUNK_LOAD_SET_LOADING';
export const SAVE_PATIENTS = 'REDUX_THUNK_SAVE_PATIENTS';
export const LOAD_USERS_ERROR = 'REDUX_THUNK_LOAD_USERS_ERROR';

//QUESTIONNAIRES
export const SAVE_QUESTIONNAIRE = 'REDUX_THUNK_SAVE_QUESTIONNAIRE';
